### ISSUE TITLE
Github Deploy

### ISSUE THREAD

**Issue by je0nh** [dre4m1ng/spring-of-loa#15]
## Description
GIthub repository를 이용해서 streamlit app을 배포합니다

## Process
1. requirements.txt, packages.txt 생성
2. .streamlit/conifg 설정
3. [Streamlit share](https://share.streamlit.io/)에서 apps 생성 후 github repo 입력
4. Deploy 확인 후 업로드 용량 늘리기

## To-Do
- [x] requirements.txt 생성
- [x] packages.txt 생성
- [x] Upload 용량 늘리기
- [x] .streamlit/conifg 설정

## Referance
- [Github repo를 이용한 streamlit 배포](https://yeomss.tistory.com/301)
- [import cv2](https://discuss.streamlit.io/t/streamlit-sharing-importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directory-opencv-error/12367/7)
- [Server upload limit](https://discuss.streamlit.io/t/how-to-limit-max-upload-size-on-share-streamlit-io/15877)
